// <auto-generated />
using System;
using AnimalsWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalsWeb.Migrations
{
    [DbContext(typeof(AnimalContext))]
    partial class AnimalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalsWeb.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            CategoryId = 1,
                            Description = "tiger (Felidae), rivaled only by the lion (Panthera leo) in strength and ferocity. The tiger is endangered throughout its range, which stretches from the Russian Far East through parts of North Korea, China, India, and Southeast",
                            Name = "Tiger",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/3/3f/Walking_tiger_female.jpg"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 4,
                            CategoryId = 2,
                            Description = "eagle, any of many large, heavy-beaked, big-footed birds of prey belonging to the family Accipitridae (order Accipitriformes) may resemble a vulture in build and flight characteristics",
                            Name = "Eagale",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/1/1a/About_to_Launch_%2826075320352%29.jpg"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 5,
                            CategoryId = 4,
                            Description = "Alligators have a long, rounded snout that has upward facing nostrils at the end; this allows breathing to occur while the rest of the body is underwater. have dark stripes on the tail. It's easy to distinguish an alligator from a crocodile by the teeth.",
                            Name = "Aligator",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/A_aligator.png/640px-A_aligator.png"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 5,
                            CategoryId = 1,
                            Description = "Wolves vary in size depending on where they live. Wolves in the north are usually larger than those in the south. The average size of a wolf. Females typically weigh 60 to 100 pounds, and males weigh 70 to 145 pounds.",
                            Name = "Wolf",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/6/68/Eurasian_wolf_2.jpg"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            CategoryId = 2,
                            Description = "The male Andean condor is a black bird with grayish white wing feathers, a white fringe of feathers around the neck, and a bare red or pinkish head, neck, and crop. Males have a large caruncle,",
                            Name = "Condor",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/0/0f/Andean_condor_%28Vultur_gryphus%29_at_Colca_Canyon.jpg"
                        });
                });

            modelBuilder.Entity("AnimalsWeb.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Mamal"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Bird"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Fish"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Reptile"
                        });
                });

            modelBuilder.Entity("AnimalsWeb.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CommentId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            AnimalId = 1,
                            Content = "the tiger color is beautiful"
                        },
                        new
                        {
                            CommentId = 2,
                            AnimalId = 2,
                            Content = " is wings are higher then me"
                        });
                });

            modelBuilder.Entity("AnimalsWeb.Models.Animal", b =>
                {
                    b.HasOne("AnimalsWeb.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AnimalsWeb.Models.Comment", b =>
                {
                    b.HasOne("AnimalsWeb.Models.Animal", "Animal")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AnimalsWeb.Models.Animal", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AnimalsWeb.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
